version: '3'

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol-data:/data/db
      - poke-vol-configdb:/data/configdb
    #ports:
    #  - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: ['--auth']
  
  mongo-express:
    depends_on:
      - db
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
    restart: always

  pokemon-nest:
    depends_on:
      - db
      - mongo-express
    container_name: pokemon-api
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - 3000:3000
    environment:
      - MONGODB=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:27017
      - DB_NAME=${MONGO_DB_NAME}
    restart: always


volumes:
  poke-vol-data:
    external: false
  poke-vol-configdb:
    external: false

#for test aplication, execute the next endpoint:
#http://localhost:3000/api/v2/pokemon?limit=20&offset=40, it get 20 pokemon info